### ISSUE TITLE
Bahia Coders

### ISSUE THREAD

**Issue by mvfsilva** [devinbahia/agenda#3]
Galera eu tinha imaginado um projeto muito parecido (igual) ao dev minas, tinha começado a fazer algumas coisas, principalmente essa questão de fazer um container de comunidades de desenvolvedores da Bahia em geral [Bahia Coders](https://github.com/bahiacoders).
O que acham de unificar os projetos?

**Comment by paulodealmeida** [comment]
Maravilha @mvfsilva vamos sim, me adiciona no projeto e vou apagar o conteúdo deste repositório

**Comment by mvfsilva** [comment]
beleza!
